# Generated by Django 5.0.2 on 2024-08-07 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='email',
            new_name='Enteremail',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='Entermessage',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='Entername',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='phoneno',
            new_name='Enterphoneno',
        ),
    ]
